- name: delete tcpdump binary
  hosts: all
  remote_user: core
  become: yes
  become_method: sudo
  tasks:
  - name: delete tcpdump
    file: 
      path: /tmp/{{ ansible_hostname }}.pcap 
      state: absent
